# Autogenerated wrapper script for P11Kit_jll for i686-w64-mingw32
export libp11kit, p11kit

JLLWrappers.@generate_wrapper_header("P11Kit")
JLLWrappers.@declare_library_product(libp11kit, "libp11-kit-0.dll")
JLLWrappers.@declare_executable_product(p11kit)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libp11kit,
        "bin\\libp11-kit-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        p11kit,
        "bin\\p11-kit.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
