# Autogenerated wrapper script for P11Kit_jll for x86_64-apple-darwin
export libp11kit, p11kit

JLLWrappers.@generate_wrapper_header("P11Kit")
JLLWrappers.@declare_library_product(libp11kit, "@rpath/libp11-kit.0.dylib")
JLLWrappers.@declare_executable_product(p11kit)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libp11kit,
        "lib/libp11-kit.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        p11kit,
        "bin/p11-kit",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
